---
- name: install required software
  hosts: centos_servers
  gather_facts: no
  become: yes
  vars:
    software:
      - git
      - telnet
      - httpd
      - wget

  tasks:
    - name: install required softwares
      package:
        name: " {{ item }} "
        state: present
      loop: "{{ software }}"